title: Predictive Business Process Monitoring with LSTM Neural Networks
description: Supplementary material for the paper submitted to CAiSE '17
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
