title: Leveraging A-priori Knowledge in Predictive Business Process Monitoring
description: Predictions of sequences of next events in the business log with A-priori knowledge.
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
